cmake_minimum_required(VERSION 3.31)
project(lab1 C)

set(CMAKE_C_STANDARD 11)

add_compile_definitions(PART_TM4C1294NCPDT)

include_directories(driverlib)
include_directories(inc)
include_directories(RTE/_Target_1)

add_executable(lab1
        driverlib/adc.c
        driverlib/adc.h
        driverlib/aes.c
        driverlib/aes.h
        driverlib/can.c
        driverlib/can.h
        driverlib/comp.c
        driverlib/comp.h
        driverlib/cpu.c
        driverlib/cpu.h
        driverlib/crc.c
        driverlib/crc.h
        driverlib/debug.h
        driverlib/des.c
        driverlib/des.h
        driverlib/eeprom.c
        driverlib/eeprom.h
        driverlib/emac.c
        driverlib/emac.h
        driverlib/epi.c
        driverlib/epi.h
        driverlib/flash.c
        driverlib/flash.h
        driverlib/fpu.c
        driverlib/fpu.h
        driverlib/gpio.c
        driverlib/gpio.h
        driverlib/hibernate.c
        driverlib/hibernate.h
        driverlib/i2c.c
        driverlib/i2c.h
        driverlib/interrupt.c
        driverlib/interrupt.h
        driverlib/lcd.c
        driverlib/lcd.h
        driverlib/mpu.c
        driverlib/mpu.h
        driverlib/onewire.c
        driverlib/onewire.h
        driverlib/pin_map.h
        driverlib/pwm.c
        driverlib/pwm.h
        driverlib/qei.c
        driverlib/qei.h
        driverlib/rom.h
        driverlib/rom_map.h
        driverlib/rtos_bindings.h
        driverlib/shamd5.c
        driverlib/shamd5.h
        driverlib/ssi.c
        driverlib/ssi.h
        driverlib/sw_crc.c
        driverlib/sw_crc.h
        driverlib/sysctl.c
        driverlib/sysctl.h
        driverlib/sysexc.c
        driverlib/sysexc.h
        driverlib/systick.c
        driverlib/systick.h
        driverlib/timer.c
        driverlib/timer.h
        driverlib/uart.c
        driverlib/uart.h
        driverlib/udma.c
        driverlib/udma.h
        driverlib/usb.c
        driverlib/usb.h
        driverlib/watchdog.c
        driverlib/watchdog.h
        inc/asmdefs.h
        inc/hw_adc.h
        inc/hw_aes.h
        inc/hw_can.h
        inc/hw_ccm.h
        inc/hw_comp.h
        inc/hw_des.h
        inc/hw_eeprom.h
        inc/hw_emac.h
        inc/hw_epi.h
        inc/hw_fan.h
        inc/hw_flash.h
        inc/hw_gpio.h
        inc/hw_hibernate.h
        inc/hw_i2c.h
        inc/hw_ints.h
        inc/hw_lcd.h
        inc/hw_memmap.h
        inc/hw_nvic.h
        inc/hw_onewire.h
        inc/hw_pwm.h
        inc/hw_qei.h
        inc/hw_shamd5.h
        inc/hw_ssi.h
        inc/hw_sysctl.h
        inc/hw_sysexc.h
        inc/hw_timer.h
        inc/hw_types.h
        inc/hw_uart.h
        inc/hw_udma.h
        inc/hw_usb.h
        inc/hw_watchdog.h
        inc/tm4c1294ncpdt.h
        RTE/_Target_1/RTE_Components.h
        RTE/Device/TM4C1294NCPDT/system_TM4C129.c
        main.c
        callback.c
        crc.c
        flash_led.c
        flash_led.h
        s800_i2c.h
        s800_i2c.c
        main.h
        control_loop.h
        control_loop.c
        s800_uart.h
        s800_uart.c
)
